spring:
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
#            naming:
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl