spring:
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.SQLServerDialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl